name: moo-instagram
author: thinkphp
current: v1.0
category: Utilities
tags: [instagram, request, photos, media, photo]
docs: https://github.com/thinkphp/moo-instagram/blob/master/docs/moo-instagram.md
demo: http://thinkphp.github.io/moo-instagram